language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - echo "building User service"
  - docker build -t udams_us ./user_service
  - docker tag udams_us olaysco/udams_us:latest
  - echo "building Feed service"
  - docker build -t udams_fs ./feed_service
  - docker tag udams_fs olaysco/udams_fs:latest
  - echo "building FE"
  - docker build -t udams_fe ./front_end
  - docker tag udams_fe olaysco/udams_fe:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push YOUR_DOCKER_HUB/simple-node
