apiVersion: apps/v1
kind: Deployment
metadata:
  name: udamsfe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udamsfe
      tier: feService
  template:
    metadata:
      labels:
        app: udamsfe
        tier: feService
    spec:
      hostname: udamsfe
      containers:
      - name: udamsfe
        image: olaysco/udams_fe
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        envFrom:
        - secretRef:
            name: appsecret
        ports:
        - name: http
          containerPort: 8080