apiVersion: v1
kind: Service
metadata:
  name: udamsfes
spec:
  selector:
    app: udamsfe
    tier: feService
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
  type: LoadBalancer