apiVersion: v1
kind: Service
metadata:
  name: udamsfe
spec:
  type: LoadBalancer
  selector:
    app: udamsfe
    tier: feService
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4200