---
apiVersion: v1
kind: Service
metadata:
  name: udamspp
spec:
  selector:
    app: udamspp
    tier: proxyPass
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer